//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package sdigital.vcpublic.config;

import java.util.Properties;
import wawo.sql.Database;

public class SystemConstant {
    public static final int DEFAULT_MENU_POSITION = 9999;
    public static final int DEFAULT_DATATABLE_ROWS = 15;
    public static Integer RECORD_PER_PAGE = 40;
    public static Integer TOP_PRODUCT_SIZE = 16;
    public static String SMTP_USER = "MAIL_USER";
    public static String SMTP_PASSWORD = "MAIL_PASSWORD";
    public static String APPLICATION_ID = "APPLICATION_ID";
    public static String ENCODING = "ENCODING";
    public static String DEFAULT_LANGUAGE_CODE = "DEFAULT_LANGUAGE_CODE";
    public static String DEFAULT_THEME = "DEFAULT_THEME";
    public static String VERSION_NUMBER = "VERSION_NUMBER";
    public static String RELEASE_DATE = "RELEASE_DATE";
    public static String SESSION_TIME_OUT_ALERT_DURATION_SEC = "SESSION_TIME_OUT_ALERT_DURATION_SEC";
    public static String DATABASE = "DATABASE";
    public static String DATABASE_POOL_NAME = "DATABASE_POOL_NAME";
    public static Database DATABASE_INSTANCE;
    public static final String TRASH = "_TRA_";
    public static final String DATA_ACCESS_LOG = "_DAL_";
    public static final Integer SUPER_ADMIN;
    public static final Integer ADMIN;
    public static final Integer DATA_ENTRY;
    public static final Integer ACTION_LIST;
    public static final Integer ACTION_CREATE;
    public static final Integer ACTION_UPDATE;
    public static final Integer ACTION_DELETE;
    public static final String STORE = "3";
    public static final String CATEGORY = "4";
    public static final String HOME = "6";
    public static final String TOP_20_V = "7";
    public static final String TOP_20_O = "8";
    public static final String TOP_20_D = "9";
    public static final String TOP_20 = "10";
    public static final String LATEST_VOUCHERS = "11";
    public static final String LATEST_DEALS = "12";
    public static final String NEW_VC = "13";
    public static final String ENDING_SOON = "14";
    public static final String EXPIRED = "15";
    public static final String ABOUT_US = "16";
    public static final String MANAGEMENT_TEAM = "17";
    public static final String PRIVACY = "18";
    public static final String HIRING = "19";
    public static final String CONTACT_US = "20";
    public static final String SIGNUP = "21";
    public static final String ALL_CATEGORIES = "22";
    public static final String ALL_STORES = "23";
    public static final String All_BRAND = "81";
    public static final String SEARCH_RESULT = "24";
    public static final String HOW_TO_USE = "54";
    public static final String STORE_CATEGORY = "53";
    public static final String STORE_BRAND = "52";
    public static final String BRAND = "51";
    public static final String COUPON_DATILS = "25";
    public static final String GUARANTEE_INFO = "26";
    public static final String ALL_SPECIALS = "27";
    public static final String SPECIAL = "60";
    public static final String ACTIVE_URL = "0";
    public static final String CAMPAIGN = "55";
    public static final String SPECIAL_CATEGORY = "70";
    public static final String EXCLUSIVE = "80";
    public static final Integer COUPON_CODES;
    public static final Integer PROMOTIONAL_CODES;
    public static final Integer PRINTABLE_CODES;
    public static final Integer OFFERS;
    public static final Integer DEALS;
    public static final Integer SALES;
    public static final String CURRENT_MONTH = "@#MONTH#@";
    public static final String CURRENT_YEAR = "@#YEAR#@";
    public static final String STORE_NAME_HOLDER = "@#STORE-NAME#@";
    public static final String VC_DOMAIN_NAME = "@#VC_DOMAIN_NAME#@";
    public static final String CATEGORY_NAME_HOLDER = "@#CATEGORY-NAME#@";
    public static final Integer CATEGORY_STORE;
    public static String SUPERADMIN_REDIRECT;
    public static String ADMIN_REDIRECT;
    public static String PATH;
    public static String CDN_IMAGE_PATH;
    public static String IMAGE_PATH;
    public static String RESOURCE_PATH;
    public static String PUBLIC;
    public static String STATIC_RESOURCE_URL;
    public static String AJAX_POPUP;
    public static String FILTERBY;
    public static String AJAX_USRPROFILE;
    public static String VOTE;
    public static String VOTE_OFFER;
    public static String FILTERBY_STORE;
    public static String COUPON_MOBILE;
    public static String LOGIN;
    public static String LOGIN_PAGE;
    public static String LOGOUT;
    public static String SIGNUPDB;
    public static String AJAX_USERCHECK;
    public static String NEWSLETTER_SUB;
    public static String NEWSLETTER_CONFIRM_SUBSCRIPTION;
    public static String NEWSLETTER_THANKYOU_SUBSCRIPTION;
    public static String FB_REDIRECTOR;
    public static String MOB_LOGIN;
    public static String CONTACT_DB;
    public static String LOAD_DATA;
    public static String ADD_COMMENT;
    public static String PROFILE;
    public static String SAVEDCOUPON;
    public static String UNSUBSCRIBE;
    public static String MORE;
    public static String FB_LOGIN;
    public static String FBLIKES;
    public static String SUBMITCOUPONDB;
    public static String ADD_STORE;
    public static String FAV_STORE;
    public static String PREFERENCES;
    public static String EDIT_PROFILE;
    public static String EDIT_PROFILEDB;
    public static String SUBMIT_COUPON;
    public static String AJAX_SEARCHKEY;
    public static String PASS;
    public static String SITEMAP;
    public static String USER_PREFERENCE;
    public static String AJAXFACEBOOK;
    public static String FBLOGIN;
    public static String NEWSLIST;
    public static String NEWSDETAIL;
    public static String ARTICLESLIST;
    public static String ARTICLESDETAIL;
    public static String SEARCH_REDIRECT;
    public static String LOGOIMAGE_PATH;
    public static String ROBOTS;
    public static String MIGRATE_UK;
    public static String COUNTRY_POPUP;
    public static String LOAD_SCREEN;
    public static String HOME_MOB;
    public static String MOBILE_URL;
    public static String MOBILE_HOME_PAGE;
    public static String OFFER_LIST;
    public static String LATEST_DEAL;
    public static String STORE_DETAIL;
    public static String CATEGORY_DETAILS;
    public static String COUPON_DETAIL;
    public static String ACTIVATE_DEAL;
    public static String MOBILE_SIGNUP;
    public static String MOBILE_SIGNUPDB;
    public static String MOBILE_AJAXUSERNAME;
    public static String MOBILE_PROFILE;
    public static String MOBILE_MYPROFILE;
    public static String MOBILE_EDIT_PROFILE;
    public static String MOBILE_LOGIN;
    public static String MOBILE_SAVED_COUPON;
    public static String LOGIN_MOBILE;
    public static String MOBILE_SEARCH_REDIRECT;
    public static String MOBILE_AJAX_SEARCHKEY;
    public static String MOBILE_SEARCH;
    public static String MOBILE_AJAX_USECOUPON;
    public static String IMAGE_PATH_MOBILE;
    public static String MOBILE_AJAX_FACEBOOK;
    public static String MOBILE_FB_LOGIN;
    public static String MOBILE_FB_REDIRECTOR;
    public static String FBAPPID_MOBILE;
    public static String MOBILE_LOGOUT;
    public static String MOB_MAX_SESSION_TIMEOUT;
    public static String MIGRATE_US;
    public static String FAQ;
    public static String CACHE_PATH;
    public static String ROOT_URL;
    public static String SEARCH_URL;
    public static String FEED_CDN;
    public static String OUT;
    public static String COUT;
    public static String SOUT;
    public static String MAX_SIMILAR_BRAND;
    public static String ENABLE_FEED_ON_SERVER;
    public static String TOP_CAT_PARAMETER;

    public SystemConstant() {
    }

    public static void load(Properties prop, String contextName) {
        SMTP_USER = prop.getProperty(SMTP_USER);
        SMTP_PASSWORD = prop.getProperty(SMTP_PASSWORD);
        APPLICATION_ID = prop.getProperty(APPLICATION_ID);
        ENCODING = prop.getProperty(ENCODING);
        DEFAULT_LANGUAGE_CODE = prop.getProperty(DEFAULT_LANGUAGE_CODE);
        DEFAULT_THEME = prop.getProperty(DEFAULT_THEME);
        VERSION_NUMBER = prop.getProperty(VERSION_NUMBER);
        RELEASE_DATE = prop.getProperty(RELEASE_DATE);
        SESSION_TIME_OUT_ALERT_DURATION_SEC = prop.getProperty(SESSION_TIME_OUT_ALERT_DURATION_SEC);
        DATABASE = prop.getProperty(DATABASE);
        DATABASE_POOL_NAME = prop.getProperty(DATABASE_POOL_NAME);
        CDN_IMAGE_PATH = prop.getProperty(CDN_IMAGE_PATH);
        IMAGE_PATH = prop.getProperty(IMAGE_PATH);
        LOGOIMAGE_PATH = prop.getProperty(LOGOIMAGE_PATH);
        PUBLIC = prop.getProperty(PUBLIC);
        RESOURCE_PATH = prop.getProperty(RESOURCE_PATH);
        PATH = prop.getProperty(PATH);
        STATIC_RESOURCE_URL = prop.getProperty(STATIC_RESOURCE_URL);
        MOBILE_URL = prop.getProperty(MOBILE_URL);
        MOBILE_HOME_PAGE = prop.getProperty(MOBILE_HOME_PAGE);
        IMAGE_PATH_MOBILE = prop.getProperty(IMAGE_PATH_MOBILE);
        FBAPPID_MOBILE = prop.getProperty(FBAPPID_MOBILE);
        MOB_MAX_SESSION_TIMEOUT = prop.getProperty(MOB_MAX_SESSION_TIMEOUT);
        if (Database.MYSQL.equals(DATABASE)) {
            DATABASE_INSTANCE = Database.MYSQL;
        } else if (Database.ORACLE.equals(DATABASE)) {
            DATABASE_INSTANCE = Database.ORACLE;
        } else if (Database.POSTGRES.equals(DATABASE)) {
            DATABASE_INSTANCE = Database.POSTGRES;
        } else if (Database.MICROSOFT_SQL_SERVER.equals(DATABASE)) {
            DATABASE_INSTANCE = Database.MICROSOFT_SQL_SERVER;
        }

        AJAX_POPUP = "/" + PUBLIC + "ajaxCouponPopup";
        FILTERBY = "/" + PUBLIC + "ajaxFilterBy";
        AJAX_USRPROFILE = "/" + PUBLIC + "ajaxUserProfile";
        VOTE = "/" + PUBLIC + "ajaxVote";
        VOTE_OFFER = "/" + PUBLIC + "ajaxVoteOffer";
        FILTERBY_STORE = "/" + PUBLIC + "ajaxFilterByStore";
        COUPON_MOBILE = "/" + PUBLIC + "mobile-coupon";
        LOGIN = "/" + PUBLIC + "login";
        LOGIN_PAGE = "/" + PUBLIC + "user-login";
        LOGOUT = "/" + PUBLIC + "logout";
        SIGNUPDB = "/" + PUBLIC + "signupdb";
        AJAX_USERCHECK = "/" + PUBLIC + "ajaxUserNameCheck";
        NEWSLETTER_SUB = "/" + PUBLIC + "newslettersub";
        NEWSLETTER_CONFIRM_SUBSCRIPTION = "/" + PUBLIC + "confirmSubscription";
        NEWSLETTER_THANKYOU_SUBSCRIPTION = "/" + PUBLIC + "newsletterthankyou";
        FB_REDIRECTOR = "/" + PUBLIC + "fbredirector";
        MOB_LOGIN = "/" + PUBLIC + "mobilelogin";
        CONTACT_DB = "/" + PUBLIC + "contactusdb";
        LOAD_DATA = "/" + PUBLIC + "load-data";
        ADD_COMMENT = "/" + PUBLIC + "addcommentdb";
        PROFILE = "/" + PUBLIC + "user-profile";
        SAVEDCOUPON = "/" + PUBLIC + "saved-coupon";
        UNSUBSCRIBE = "/" + PUBLIC + "unsubscribe";
        MORE = "/" + PUBLIC + "ajaxLoadMore";
        FB_LOGIN = "/" + PUBLIC + "fblogin";
        FBLIKES = "/" + PUBLIC + "fblikes";
        SUBMITCOUPONDB = "/" + PUBLIC + "submitcoupondb";
        ADD_STORE = "/" + PUBLIC + "add-stores";
        FAV_STORE = "/" + PUBLIC + "favourite-stores";
        PREFERENCES = "/" + PUBLIC + "user-preferences";
        EDIT_PROFILE = "/" + PUBLIC + "edit-profile";
        EDIT_PROFILEDB = "/" + PUBLIC + "editprofiledb";
        SUBMIT_COUPON = "/" + PUBLIC + "ajaxCoupon";
        AJAX_SEARCHKEY = "/" + PUBLIC + "ajaxSearchKey";
        SITEMAP = "/" + PUBLIC + "sitemap.xml";
        USER_PREFERENCE = "/" + PUBLIC + "userPreferencedb";
        AJAXFACEBOOK = "/" + PUBLIC + "ajaxFacebook";
        FBLOGIN = "/" + PUBLIC + "fblogin";
        NEWSLIST = "/" + PUBLIC + "news";
        NEWSDETAIL = "/" + PUBLIC + "news-detail";
        ARTICLESLIST = "/" + PUBLIC + "articles";
        ARTICLESDETAIL = "/" + PUBLIC + "articles-detail";
        SEARCH_REDIRECT = "/" + PUBLIC + "searchRedirect";
        ROBOTS = "/" + PUBLIC + "robots.txt";
        MIGRATE_UK = "/" + PUBLIC + "migrate-uk";
        COUNTRY_POPUP = "/" + PUBLIC + "vc-mobile/ajaxCountryPopup";
        LOAD_SCREEN = "/" + PUBLIC + "vc-mobile/loadScreen";
        HOME_MOB = "/" + PUBLIC + "vc-mobile/home";
        OFFER_LIST = "/" + PUBLIC + "vc-mobile/offerlist";
        LATEST_DEAL = "/" + PUBLIC + "vc-mobile/ajaxLatestDeal";
        STORE_DETAIL = "/" + PUBLIC + "vc-mobile/storeDetail";
        CATEGORY_DETAILS = "/" + PUBLIC + "vc-mobile/categoryDetails";
        COUPON_DETAIL = "/" + PUBLIC + "vc-mobile/couponDetail";
        ACTIVATE_DEAL = "/" + PUBLIC + "vc-mobile/activateDeal";
        MOBILE_SIGNUP = "/" + PUBLIC + "vc-mobile/signUp";
        MOBILE_SIGNUPDB = "/" + PUBLIC + "vc-mobile/signUpDb";
        MOBILE_AJAXUSERNAME = "/" + PUBLIC + "vc-mobile/ajaxUserName";
        MOBILE_PROFILE = "/" + PUBLIC + "vc-mobile/profile";
        MOBILE_MYPROFILE = "/" + PUBLIC + "vc-mobile/myProfile";
        MOBILE_EDIT_PROFILE = "/" + PUBLIC + "vc-mobile/editProfileDB";
        MOBILE_SEARCH_REDIRECT = "/" + PUBLIC + "vc-mobile/searchRedirect";
        MOBILE_AJAX_SEARCHKEY = "/" + PUBLIC + "vc-mobile/ajaxSearchKey";
        MOBILE_LOGIN = "/" + PUBLIC + "vc-mobile/login";
        MOBILE_SAVED_COUPON = "/" + PUBLIC + "vc-mobile/ajaxSavedCoupon";
        LOGIN_MOBILE = "/" + PUBLIC + "vc-mobile/mobLogin";
        MOBILE_SEARCH = "/" + PUBLIC + "vc-mobile/search";
        MOBILE_AJAX_USECOUPON = "/" + PUBLIC + "vc-mobile/ajaxUseCoupon";
        MOBILE_AJAX_FACEBOOK = "/" + PUBLIC + "vc-mobile/ajaxLoginFb";
        MOBILE_FB_LOGIN = "/" + PUBLIC + "vc-mobile/fbLogin";
        MOBILE_FB_REDIRECTOR = "/" + PUBLIC + "vc-mobile/fbredirector";
        MOBILE_LOGOUT = "/" + PUBLIC + "vc-mobile/logout";
        MIGRATE_US = "/" + PUBLIC + "migrate-us";
        FAQ = "/" + PUBLIC + "faq";
        OUT = "/" + PUBLIC + "out";
        COUT = "/" + PUBLIC + "cout";
        SOUT = "/" + PUBLIC + "sout";
        CACHE_PATH = prop.getProperty(CACHE_PATH);
        ROOT_URL = prop.getProperty(ROOT_URL);
        SEARCH_URL = prop.getProperty(SEARCH_URL);
        FEED_CDN = prop.getProperty(FEED_CDN);
        MAX_SIMILAR_BRAND = prop.getProperty(MAX_SIMILAR_BRAND);
        ENABLE_FEED_ON_SERVER = prop.getProperty(ENABLE_FEED_ON_SERVER);
        TOP_CAT_PARAMETER = prop.getProperty(TOP_CAT_PARAMETER);
    }

    static {
      //  DATABASE_INSTANCE = Database.ANY_DATABASE;
        SUPER_ADMIN = 1;
        ADMIN = 2;
        DATA_ENTRY = 3;
        ACTION_LIST = 1;
        ACTION_CREATE = 2;
        ACTION_UPDATE = 3;
        ACTION_DELETE = 4;
        COUPON_CODES = 1;
        PROMOTIONAL_CODES = 2;
        PRINTABLE_CODES = 3;
        OFFERS = 4;
        DEALS = 5;
        SALES = 6;
        CATEGORY_STORE = 53;
        SUPERADMIN_REDIRECT = "/admin/gl_language_list.xhtml";
        ADMIN_REDIRECT = "/admin/category_domain_configuration.xhtml";
        PATH = "PATH";
        CDN_IMAGE_PATH = "CDN_IMAGE_PATH";
        IMAGE_PATH = "IMAGE_PATH";
        RESOURCE_PATH = "RESOURCE_PATH";
        PUBLIC = "PUBLIC";
        STATIC_RESOURCE_URL = "STATIC_RESOURCE_URL";
        AJAX_POPUP = "AJAX_POPUP";
        FILTERBY = "FILTERBY";
        AJAX_USRPROFILE = "AJAX_USRPROFILE";
        VOTE = "VOTE";
        VOTE_OFFER = "VOTE_OFFER";
        FILTERBY_STORE = "FILTERBY_STORE";
        COUPON_MOBILE = "COUPON_MOBILE";
        LOGIN = "LOGIN";
        LOGIN_PAGE = "LOGIN_PAGE";
        LOGOUT = "LOGOUT";
        SIGNUPDB = "SIGNUPDB";
        AJAX_USERCHECK = "AJAX_USERCHECK";
        NEWSLETTER_SUB = "NEWSLETTER_SUB";
        NEWSLETTER_CONFIRM_SUBSCRIPTION = "NEWSLETTER_CONFIRM_SUBSCRIPTION";
        NEWSLETTER_THANKYOU_SUBSCRIPTION = "NEWSLETTER_THANKYOU_SUBSCRIPTION";
        FB_REDIRECTOR = "FB_REDIRECTOR";
        MOB_LOGIN = "MOB_LOGIN";
        CONTACT_DB = "CONTACT_DB";
        LOAD_DATA = "LOAD_DATA";
        ADD_COMMENT = "ADD_COMMENT";
        PROFILE = "PROFILE";
        SAVEDCOUPON = "SAVEDCOUPON";
        UNSUBSCRIBE = "UNSUBSCRIBE";
        MORE = "MORE";
        FB_LOGIN = "FB_LOGIN";
        FBLIKES = "FBLIKES";
        SUBMITCOUPONDB = "SUBMITCOUPONDB";
        ADD_STORE = "ADD_STORE";
        FAV_STORE = "FAV_STORE";
        PREFERENCES = "PREFERENCES";
        EDIT_PROFILE = "EDIT_PROFILE";
        EDIT_PROFILEDB = "EDIT_PROFILEDB";
        SUBMIT_COUPON = "SUBMIT_COUPON";
        AJAX_SEARCHKEY = "AJAX_SEARCHKEY";
        PASS = "welcome2vc";
        SITEMAP = "SITEMAP";
        USER_PREFERENCE = "USER_PREFERENCE";
        AJAXFACEBOOK = "AJAXFACEBOOK";
        FBLOGIN = "FBLOGIN";
        NEWSLIST = "NEWSLIST";
        NEWSDETAIL = "NEWSDETAIL";
        ARTICLESLIST = "ARTICLESLIST";
        ARTICLESDETAIL = "ARTICLESDETAIL";
        SEARCH_REDIRECT = "SEARCH_REDIRECT";
        LOGOIMAGE_PATH = "LOGOIMAGE_PATH";
        ROBOTS = "ROBOTS";
        MIGRATE_UK = "MIGRATE_UK";
        COUNTRY_POPUP = "COUNTRY_POPUP";
        LOAD_SCREEN = "LOAD_SCREEN";
        HOME_MOB = "HOME_MOB";
        MOBILE_URL = "MOBILE_URL";
        MOBILE_HOME_PAGE = "MOBILE_HOME_PAGE";
        OFFER_LIST = "OFFER_LIST";
        LATEST_DEAL = "LATEST_DEAL";
        STORE_DETAIL = "STORE_DETAIL";
        CATEGORY_DETAILS = "CATEGORY_DETAILS";
        COUPON_DETAIL = "COUPON_DETAIL";
        ACTIVATE_DEAL = "ACTIVATE_DEAL";
        MOBILE_SIGNUP = "MOBILE_SIGNUP";
        MOBILE_SIGNUPDB = "MOBILE_SIGNUPDB";
        MOBILE_AJAXUSERNAME = "MOBILE_AJAXUSERNAME";
        MOBILE_PROFILE = "MOBILE_PROFILE";
        MOBILE_MYPROFILE = "MOBILE_MYPROFILE";
        MOBILE_EDIT_PROFILE = "MOBILE_EDIT_PROFILE";
        MOBILE_LOGIN = "MOBILE_LOGIN";
        MOBILE_SAVED_COUPON = "MOBILE_SAVED_COUPON";
        LOGIN_MOBILE = "LOGIN_MOBILE";
        MOBILE_SEARCH_REDIRECT = "MOBILE_SEARCH_REDIRECT";
        MOBILE_AJAX_SEARCHKEY = "MOBILE_AJAX_SEARCHKEY";
        MOBILE_SEARCH = "MOBILE_SEARCH";
        MOBILE_AJAX_USECOUPON = "MOBILE_AJAX_USECOUPON";
        IMAGE_PATH_MOBILE = "IMAGE_PATH_MOBILE";
        MOBILE_AJAX_FACEBOOK = "MOBILE_AJAX_FACEBOOK";
        MOBILE_FB_LOGIN = "MOBILE_FB_LOGIN";
        MOBILE_FB_REDIRECTOR = "MOBILE_FB_REDIRECTOR";
        FBAPPID_MOBILE = "FBAPPID_MOBILE";
        MOBILE_LOGOUT = "MOBILE_LOGOUT";
        MOB_MAX_SESSION_TIMEOUT = "MOB_MAX_SESSION_TIMEOUT";
        MIGRATE_US = "MIGRATE_US";
        FAQ = "FAQ";
        CACHE_PATH = "CACHE_PATH";
        ROOT_URL = "ROOT_URL";
        SEARCH_URL = "SEARCH_URL";
        FEED_CDN = "FEED_CDN";
        OUT = "OUT";
        COUT = "COUT";
        SOUT = "SOUT";
        MAX_SIMILAR_BRAND = "MAX_SIMILAR_BRAND";
        ENABLE_FEED_ON_SERVER = "ENABLE_FEED_ON_SERVER";
        TOP_CAT_PARAMETER = "TOP_CAT_PARAMETER";
    }
}
